### PR TITLE
[#11] Add MIT license to gemspec

### PR DESCRIPTION
**Pull request by bf4**
Per #11

### CODE REVIEW

**Comment by jeffremer** [comment]
Nice, thanks @bf4 - I'll merge this, it closes #11 - then I'll cut a new version and push it to Rubygems shortly. Thanks again!

**Comment by bf4** [comment]
Sure, it's been fun doing this

**Comment by jeffremer** [comment]
Done, 0.0.8 is on rubygems.org - I've also added you to the contributors list in the README.md

**Comment by bf4** [comment]
Thanks, though no need :)

**Pull request merged**
