### PR TITLE
typo on the longitude

### PR DESCRIPTION
**Pull request by jameshwang**
Hi, thank you for setting up this gem.  It looks like a great wrapper for the muni api.

I just noticed the typo regarding longitude.  It was getting latitude values.

Let me know if you have any questions.

Thanks!
James

### CODE REVIEW

**Comment by jeffremer** [comment]
Nice, thanks @jameshwang, much appreciated. If you don't mind adding a test to cover this that'd be fantastic, otherwise don't worry about it too much.

**Comment by jameshwang** [comment]
@jeffremer let me know if this test is good enough.  Otherwise, thanks!

**Comment by jeffremer** [comment]
LGTM  :+1: Thanks a bunch @jameshwang, I'll merge this then cut a new dot release shortly.

**Comment by jeffremer** [comment]
@jameshwang following up, I just pushed 0.0.7 to Rubygems which includes your change. Thank you!

**Comment by jameshwang** [comment]
@jeffremer great! Thanks Jeff! Happy to help

**Pull request merged**
